---
nftables_config:
  vars:
    lan_network: 10.20.10.0/24
    wan_interface: eth0
    lan_interface: eth1
  tables:
    firewall:
      type: inet
      chains:
        input:
          hook: input
          policy: drop
          rules:
            - raw: ct state invalid drop
            - raw: ct state { established, related } accept
            - raw: iifname lo accept
            - raw: ip protocol icmp accept
            - raw: tcp dport 22 accept
            - raw: iifname $lan_interface ip protocol 112 accept
            - raw: iifname $lan_interface udp dport 3780 accept
            - raw: iifname $wan_interface udp dport 51820 accept
            - raw: iifname $lan_interface udp dport 51820 accept
        forward:
          hook: forward
          policy: drop
          rules:
            - raw: ct state invalid drop
            - raw: ct state { established, related } accept
            - raw: >-
                iifname $lan_interface oifname $wan_interface
                ip saddr $lan_network accept
            - raw: >-
                iifname $wan_interface oifname $lan_interface
                tcp dport { 80, 443 } ip daddr 10.20.10.10 accept
            - raw: >-
                iifname "wg0" oifname $wan_interface
                ip daddr 10.10.10.0/24 accept
            - raw: >-
                iifname "wg0" oifname $lan_interface
                ip daddr 10.20.10.0/24 accept
            - raw: >-
                iifname $wan_interface oifname $lan_interface
                tcp dport { 25, 465, 587, 993 }
                ip daddr 10.20.10.80 accept
        output:
          hook: output
          policy: accept
        postrouting:
          type: nat
          hook: postrouting
          policy: accept
          rules:
            - raw: oifname $wan_interface ip saddr $lan_network masquerade
            - raw: ip saddr 10.100.0.0/30 masquerade
        prerouting:
          type: nat
          hook: prerouting
          policy: accept
          rules:
            - raw: >-
                iifname $wan_interface tcp dport 80 dnat ip to 10.20.10.10:80
            - raw: >-
                iifname $wan_interface tcp dport 443 dnat ip to 10.20.10.10:443
            - raw: >-
                iifname $wan_interface tcp dport { 25, 465, 587, 993 }
                dnat ip to 10.20.10.80
frr_enabled: false
keepalived_enabled: true
conntrackd_enabled: true
strongswan_enabled: true
frr_daemons: []
keepalived_virtual_ipaddresses:
  - address: 10.10.10.2
    prefix: 24
    interface: eth0
  - address: 10.20.10.2
    prefix: 24
    interface: eth1
keepalived_password: ha
keepalived_ha_interface: eth1
keepalived_virtual_ip: 10.20.10.2
keepalived_virtual_ip_prefix: 24
conntrackd_multicast_address: 239.0.0.1
keepalived_virtual_ipaddress: >-
  {{ keepalived_virtual_ip }}/{{ keepalived_virtual_ip_prefix }}
  dev {{ keepalived_ha_interface }}

strongswan_connections: {}

wireguard_enabled: true
wireguard_vip_address: "10.10.10.2/24"
wireguard_key_mode: shared
wireguard_shared_private_key: ""
wireguard_interfaces:
  - name: wg0
    address: 10.100.0.1/30
    listen_port: 51820
    peers:
      - public_key: "Th4iePA5MCx60pmIkfTN0RFbuLBiaaD+s08+Bwm/enA="
        allowed_ips:
          - 10.100.0.2/32
        persistent_keepalive: 25
