---
firux_nftables_config:
  vars:
    lan_network: 10.20.10.0/24
    wan_interface: eth0
    lan_interface: eth1
  tables:
    firewall:
      type: inet
      chains:
        input:
          hook: input
          policy: drop
          rules:
            - raw: ct state invalid drop
            - raw: ct state { established, related } accept
            - raw: iifname lo accept
            - raw: ip protocol icmp accept
            - raw: tcp dport 22 accept
            - raw: iifname $lan_interface ip protocol 112 accept
            - raw: iifname $lan_interface udp dport 3780 accept
        forward:
          hook: forward
          policy: drop
          rules:
            - raw: ct state invalid drop
            - raw: ct state { established, related } accept
            - raw: >-
                iifname $lan_interface oifname $wan_interface
                ip saddr $lan_network accept
            - raw: >-
                iifname $wan_interface oifname $lan_interface
                tcp dport { 80, 443 } ip daddr 10.20.10.10 accept
        output:
          hook: output
          policy: accept
        postrouting:
          type: nat
          hook: postrouting
          policy: accept
          rules:
            - raw: oifname $wan_interface ip saddr $lan_network masquerade
        prerouting:
          type: nat
          hook: prerouting
          policy: accept
          rules:
            - raw: >-
                iifname $wan_interface tcp dport 80 dnat ip to 10.20.10.10:80
            - raw: >-
                iifname $wan_interface tcp dport 443 dnat ip to 10.20.10.10:443
firux_wireguard_interfaces: []
firux_wireguard_enabled: false
firux_frr_enabled: false
firux_keepalived_enabled: true
firux_conntrackd_enabled: true
firux_strongswan_enabled: false
firux_frr_daemons: []
firux_keepalived_password: firux-ha
firux_keepalived_ha_interface: eth1
firux_keepalived_virtual_ip: 10.20.10.5
firux_keepalived_virtual_ip_prefix: 24
firux_conntrackd_multicast_address: 239.0.0.1
firux_keepalived_virtual_ipaddress: >-
  {{ firux_keepalived_virtual_ip }}/{{ firux_keepalived_virtual_ip_prefix }}
  dev {{ firux_keepalived_ha_interface }}

firux_strongswan_connections: {}

firux_wireguard_enabled: true

firux_wireguard_interfaces:
  - name: wg0
    address: 10.100.0.1/30
    listen_port: 51820
    # peers:
    #   - public_key: "CLE_PUBLIQUE_PEER"
    #     allowed_ips:
    #       - 10.100.0.2/32
    #     endpoint: 203.0.113.10:51820
    #     persistent_keepalive: 25
