---
- name: Redémarrer systemd-networkd
  ansible.builtin.systemd:
    name: systemd-networkd
    state: restarted
    enabled: true

- name: Recharger les paramètres sysctl
  ansible.builtin.command: sysctl --system
  changed_when: true
