---
- name: Déployer Firux sur les firewalls Debian 13
  hosts: grp1
  become: true
  roles:
    - firux.system
    - firux.network
    - firux.nftables
    - firux.wireguard
    - firux.strongswan
    - firux.frr
    - firux.keepalived
    - firux.conntrackd
