---
- name: Déployer Firux sur les firewalls Debian 13
  hosts: grp1
  become: true
  roles:
    - firux.system
    - firux.nftables
    - role: firux.wireguard
      when: firux_wireguard_enabled
    - role: firux.strongswan
      when: firux_strongswan_enabled
    - role: firux.frr
      when: firux_frr_enabled
    - role: firux.keepalived
      when: firux_keepalived_enabled
    - role: firux.conntrackd
      when: firux_conntrackd_enabled
