---
- name: Déployer Firux sur les firewalls Debian 13
  hosts: grp1
  become: true
  roles:
    - system
    - network
    - nftables
    - wireguard
    - strongswan
    - frr
    - keepalived
    - conntrackd
