---
- name: Configurer strongSwan
  block:
    - name: Installer strongSwan
      ansible.builtin.apt:
        name: "{{ strongswan_packages }}"
        state: present
        update_cache: true

    - name: Déployer les secrets strongSwan
      ansible.builtin.template:
        src: ipsec.secrets.j2
        dest: /etc/ipsec.secrets
        owner: root
        group: root
        mode: "0600"
      when: strongswan_connections | length > 0
      notify: Redémarrer strongSwan

    - name: Déployer la configuration strongSwan
      ansible.builtin.template:
        src: ipsec.conf.j2
        dest: /etc/ipsec.conf
        owner: root
        group: root
        mode: "0600"
      when: strongswan_connections | length > 0
      notify: Redémarrer strongSwan

- name: Activer strongswan au boot (standalone)
  ansible.builtin.systemd:
    name: strongswan-starter
    state: started
    enabled: true
  when:
    - strongswan_enabled
    - not keepalived_enabled

- name: Désactiver strongswan au boot (HA)
  ansible.builtin.systemd:
    name: strongswan-starter
    state: stopped
    enabled: false
  when:
    - strongswan_enabled
    - keepalived_enabled
