---
- name: Installer keepalived
  ansible.builtin.apt:
    name: keepalived
    state: present
    update_cache: true
- name: Déployer keepalived
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: "0600"
    validate: keepalived --config-test --use-file %s
  notify: Redémarrer keepalived
