---
- block:
    - name: Installer FRR
      ansible.builtin.apt:
        name: frr
        state: present
        update_cache: true
    - name: Déployer les daemons FRR
      ansible.builtin.template:
        src: daemons.j2
        dest: /etc/frr/daemons
        owner: frr
        group: frr
        mode: "0640"
      notify: Redémarrer frr
    - name: Déployer les configurations FRR
      ansible.builtin.copy:
        content: "{{ item.value }}"
        dest: "/etc/frr/{{ item.key }}.conf"
        owner: frr
        group: frr
        mode: "0640"
      loop: "{{ firux_frr_configs | dict2items }}"
      notify: Redémarrer frr
  when: firux_frr_enabled
