---
- name: Vérifier Debian 13
  ansible.builtin.assert:
    that:
      - ansible_facts.os_family == "Debian"
      - ansible_facts.distribution_major_version | int == 13
- name: Configurer les paramètres système
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    sysctl_set: true
    reload: true
  loop: "{{ firux_system_sysctls | dict2items }}"
