---
- block:
    - name: Installer keepalived
      ansible.builtin.apt:
        name: keepalived
        state: present
        update_cache: true

    - name: Déployer le script keepalived MASTER
      ansible.builtin.template:
        src: notify-master.sh.j2
        dest: /usr/local/sbin/firux-keepalived-master
        owner: root
        group: root
        mode: "0750"

    - name: Déployer le script keepalived BACKUP
      ansible.builtin.template:
        src: notify-backup.sh.j2
        dest: /usr/local/sbin/firux-keepalived-backup
        owner: root
        group: root
        mode: "0750"

    - name: Déployer keepalived
      ansible.builtin.template:
        src: keepalived.conf.j2
        dest: /etc/keepalived/keepalived.conf
        owner: root
        group: root
        mode: "0600"
        validate: keepalived --config-test --use-file %s
      notify: Redémarrer keepalived
  when: keepalived_enabled
